with
data_max as (
  select 
    max(r.rental_date) as max_data --data mais recente
  from rental r

),
periodos as (

  select 
    r.customer_id,
    r.rental_date,
    case 
      when r.rental_date >= d.max_data - interval '3 months' then 'ultimos_3' --pega a data do aluguel e compara com a data mais recente, se for maior ou igual a data mais recente - 3 meses, então é considerado aluguel dos ultimos 3 meses
      when r.rental_date >= d.max_data - interval '6 months' and r.rental_date < d.max_data - interval '3 months'  then '3_anteriores' --pega a data do aluguel e compara com a data mais recente, se for maior ou igual a data mais recente - 6 meses e menor que a data mais recente - 3 meses, então é considerado aluguel dos 3 meses anteriores
    end as periodo
  from rental r 
  cross join data_max d 

)SELECT
    p.customer_id as "ID",
    concat(c.first_name, ' ', c.last_name)as "Nome",

    COUNT(*) FILTER (WHERE p.periodo = 'ultimos_3') AS ultimos_3,--pega a quantidade de aluguel dos ultimos 3 meses

    COUNT(*) FILTER (WHERE p.periodo = '3_anteriores') AS anteriores_3--pega a quantidade de aluguel dos 3 meses anteriores

FROM periodos p 
join customer c on c.customer_id = p.customer_id
WHERE periodo IS NOT NULL
GROUP BY p.customer_id, "Nome"
HAVING
    COUNT(*) FILTER (WHERE periodo = 'ultimos_3')
    <
    COUNT(*) FILTER (WHERE periodo = '3_anteriores') --trazer apenas os clientes que alugaram mais filmes nos 3 meses anteriores do que nos ultimos 3 meses
order by "Nome" asc;


| ID  | Nome                  | ultimos_3 | anteriores_3 |
| --- | --------------------- | --------- | ------------ |
| 375 | Aaron Selby           | 0         | 5            |
| 367 | Adam Gooch            | 0         | 7            |
| 525 | Adrian Clary          | 1         | 3            |
| 217 | Agnes Bishop          | 0         | 6            |
| 389 | Alan Kahn             | 0         | 7            |
| 352 | Albert Crouse         | 1         | 7            |
| 568 | Alberto Henning       | 1         | 3            |
| 454 | Alex Gresham          | 0         | 11           |
| 439 | Alexander Fennell     | 0         | 12           |
| 423 | Alfred Casillas       | 0         | 6            |
| 567 | Alfredo Mcadams       | 0         | 6            |
| 51  | Alice Stewart         | 0         | 12           |
| 152 | Alicia Mills          | 1         | 10           |
| 548 | Allan Cornish         | 1         | 5            |
| 412 | Allen Butterfield     | 1         | 5            |
| 228 | Allison Stanley       | 2         | 3            |
| 196 | Alma Austin           | 0         | 7            |
| 467 | Alvin Deloach         | 0         | 9            |
| 40  | Amanda Carter         | 0         | 10           |
| 139 | Amber Dixon           | 0         | 10           |
| 32  | Amy Lopez             | 0         | 6            |
| 181 | Ana Bradley           | 1         | 10           |
| 515 | Andre Rapp            | 0         | 10           |
| 81  | Andrea Henderson      | 0         | 11           |
| 333 | Andrew Purdy          | 0         | 8            |
| 582 | Andy Vanhorn          | 1         | 9            |
| 503 | Angel Barclay         | 0         | 13           |
| 29  | Angela Hernandez      | 1         | 13           |
| 136 | Anita Morales         | 0         | 7            |
| 48  | Ann Evans             | 0         | 3            |
| 33  | Anna Hill             | 1         | 7            |
| 85  | Anne Powell           | 0         | 4            |
| 175 | Annette Olson         | 2         | 7            |
| 97  | Annie Russell         | 0         | 2            |
| 320 | Anthony Schwab        | 0         | 3            |
| 398 | Antonio Meek          | 0         | 3            |
| 142 | April Burns           | 1         | 8            |
| 225 | Arlene Harvey         | 0         | 1            |
| 556 | Armando Gruber        | 0         | 4            |
| 522 | Arnold Havens         | 0         | 6            |
| 346 | Arthur Simpkins       | 0         | 6            |
| 63  | Ashley Richardson     | 0         | 9            |
| 173 | Audrey Ray            | 0         | 7            |
| 599 | Austin Cintron        | 0         | 7            |
| 4   | Barbara Jones         | 0         | 9            |
| 438 | Barry Lovelace        | 1         | 7            |
| 170 | Beatrice Arnold       | 0         | 7            |
| 287 | Becky Miles           | 1         | 7            |
| 510 | Ben Easter            | 0         | 4            |
| 364 | Benjamin Varney       | 0         | 8            |
| 440 | Bernard Colby         | 1         | 8            |
| 172 | Bernice Willis        | 0         | 11           |
| 156 | Bertha Ferguson       | 0         | 8            |
| 221 | Bessie Morrison       | 0         | 10           |
| 199 | Beth Franklin         | 1         | 4            |
| 14  | Betty White           | 1         | 6            |
| 73  | Beverly Brooks        | 1         | 5            |
| 457 | Bill Gavin            | 2         | 9            |
| 278 | Billie Horton         | 0         | 8            |
| 371 | Billy Poulin          | 0         | 9            |
| 564 | Bob Pfeiffer          | 0         | 9            |
| 288 | Bobbie Craig          | 0         | 9            |
| 381 | Bobby Boudreau        | 0         | 11           |
| 88  | Bonnie Hughes         | 0         | 4            |
| 517 | Brad Mccurdy          | 0         | 5            |
| 426 | Bradley Motley        | 0         | 8            |
| 366 | Brandon Huey          | 1         | 10           |
| 276 | Brandy Graves         | 0         | 9            |
| 31  | Brenda Wright         | 0         | 4            |
| 493 | Brent Harkins         | 1         | 7            |
| 502 | Brett Cornwell        | 0         | 6            |
| 318 | Brian Wyman           | 0         | 1            |
| 187 | Brittany Riley        | 0         | 9            |
| 365 | Bruce Schwarz         | 0         | 5            |
| 400 | Bryan Hardison        | 0         | 8            |
| 573 | Byron Box             | 0         | 6            |
| 453 | Calvin Martel         | 0         | 10           |
| 345 | Carl Artis            | 0         | 5            |
| 202 | Carla Gutierrez       | 0         | 7            |
| 379 | Carlos Coughlin       | 0         | 11           |
| 111 | Carmen Owens          | 1         | 5            |
| 18  | Carol Garcia          | 0         | 2            |
| 275 | Carole Barnett        | 0         | 14           |
| 248 | Caroline Bowman       | 0         | 4            |
| 42  | Carolyn Perez         | 2         | 4            |
| 129 | Carrie Porter         | 0         | 8            |
| 566 | Casey Mena            | 0         | 7            |
| 269 | Cassandra Walters     | 2         | 7            |
| 46  | Catherine Campbell    | 0         | 13           |
| 163 | Cathy Spencer         | 2         | 9            |
| 512 | Cecil Vines           | 1         | 11           |
| 419 | Chad Carbone          | 0         | 5            |
| 220 | Charlene Alvarez      | 0         | 8            |
| 306 | Charles Kowalski      | 0         | 10           |
| 495 | Charlie Bess          | 1         | 6            |
| 130 | Charlotte Hunter      | 0         | 6            |
| 59  | Cheryl Murphy         | 0         | 9            |
| 511 | Chester Benner        | 0         | 5            |
| 394 | Chris Brothers        | 1         | 5            |
| 534 | Christian Jung        | 1         | 5            |
| 70  | Christina Ramirez     | 0         | 8            |
| 43  | Christine Roberts     | 2         | 7            |
| 309 | Christopher Greco     | 0         | 6            |
| 260 | Christy Vargas        | 0         | 9            |
| 113 | Cindy Fisher          | 0         | 7            |
| 144 | Clara Shaw            | 0         | 10           |
| 391 | Clarence Gamez        | 0         | 5            |
| 528 | Claude Herzog         | 0         | 5            |
| 234 | Claudia Fuller        | 1         | 7            |
| 551 | Clayton Barbee        | 0         | 10           |
| 447 | Clifford Bowens       | 0         | 8            |
| 577 | Clifton Malcolm       | 0         | 7            |
| 537 | Clinton Buford        | 1         | 7            |
| 485 | Clyde Tobias          | 0         | 5            |
| 544 | Cody Nolen            | 0         | 8            |
| 227 | Colleen Burton        | 1         | 4            |
| 106 | Connie Wallace        | 0         | 5            |
| 232 | Constance Reid        | 0         | 6            |
| 480 | Corey Hauser          | 0         | 6            |
| 527 | Cory Meehan           | 1         | 6            |
| 245 | Courtney Day          | 1         | 3            |
| 388 | Craig Morrell         | 1         | 11           |
| 102 | Crystal Ford          | 0         | 4            |
| 410 | Curtis Irby           | 1         | 12           |
| 28  | Cynthia Young         | 1         | 8            |
| 295 | Daisy Bates           | 1         | 6            |
| 407 | Dale Ratcliff         | 0         | 9            |
| 477 | Dan Paine             | 0         | 5            |
| 179 | Dana Hart             | 0         | 7            |
| 310 | Daniel Cabral         | 0         | 4            |
| 150 | Danielle Daniels      | 0         | 14           |
| 399 | Danny Isom            | 0         | 5            |
| 157 | Darlene Rose          | 0         | 8            |
| 463 | Darrell Power         | 0         | 7            |
| 541 | Darren Windham        | 0         | 11           |
| 530 | Darryl Ashcraft       | 1         | 6            |
| 579 | Daryl Larue           | 1         | 8            |
| 569 | Dave Gardiner         | 0         | 13           |
| 304 | David Royal           | 0         | 6            |
| 105 | Dawn Sullivan         | 0         | 8            |
| 471 | Dean Sauer            | 0         | 10           |
| 261 | Deanna Byrd           | 0         | 8            |
| 141 | Debbie Reyes          | 0         | 12           |
| 25  | Deborah Walker        | 0         | 6            |
| 39  | Debra Nelson          | 0         | 4            |
| 222 | Delores Hansen        | 0         | 3            |
| 74  | Denise Kelly          | 0         | 11           |
| 338 | Dennis Gilman         | 0         | 7            |
| 461 | Derek Blakely         | 0         | 11           |
| 476 | Derrick Bourque       | 1         | 3            |
| 96  | Diana Alexander       | 0         | 8            |
| 50  | Diane Collins         | 0         | 6            |
| 279 | Dianne Shelton        | 1         | 13           |
| 171 | Dolores Wagner        | 0         | 8            |
| 433 | Don Bone              | 0         | 8            |
| 313 | Donald Mahon          | 0         | 7            |
| 17  | Donna Thompson        | 0         | 6            |
| 249 | Dora Medina           | 0         | 4            |
| 55  | Doris Reed            | 0         | 6            |
| 10  | Dorothy Taylor        | 0         | 5            |
| 343 | Douglas Graf          | 0         | 5            |
| 513 | Duane Tubbs           | 0         | 11           |
| 474 | Dustin Gillette       | 1         | 9            |
| 554 | Dwayne Olvera         | 0         | 10           |
| 555 | Dwight Lombardi       | 0         | 8            |
| 396 | Earl Shanks           | 0         | 9            |
| 434 | Eddie Tomlin          | 0         | 9            |
| 507 | Edgar Rhoads          | 0         | 5            |
| 117 | Edith Mcdonald        | 0         | 7            |
| 109 | Edna West             | 0         | 4            |
| 594 | Eduardo Hiatt         | 0         | 2            |
| 317 | Edward Baugh          | 1         | 10           |
| 432 | Edwin Burk            | 0         | 5            |
| 205 | Eileen Carr           | 0         | 6            |
| 127 | Elaine Stevens        | 0         | 8            |
| 148 | Eleanor Hunt          | 0         | 16           |
| 5   | Elizabeth Brown       | 1         | 9            |
| 210 | Ella Oliver           | 0         | 9            |
| 126 | Ellen Simpson         | 0         | 10           |
| 516 | Elmer Noe             | 2         | 7            |
| 198 | Elsie Kelley          | 0         | 14           |
| 99  | Emily Diaz            | 1         | 2            |
| 134 | Emma Boyd             | 0         | 5            |
| 596 | Enrique Forsythe      | 1         | 9            |
| 331 | Eric Robert           | 0         | 7            |
| 169 | Erica Matthews        | 0         | 8            |
| 529 | Erik Guillen          | 0         | 11           |
| 298 | Erika Pena            | 0         | 8            |
| 160 | Erin Dunn             | 0         | 10           |
| 384 | Ernest Stepp          | 0         | 6            |
| 132 | Esther Crawford       | 0         | 3            |
| 125 | Ethel Webb            | 0         | 8            |
| 378 | Eugene Culpepper      | 0         | 4            |
| 140 | Eva Ramos             | 0         | 5            |
| 57  | Evelyn Morgan         | 0         | 6            |
| 559 | Everett Banda         | 0         | 8            |
| 283 | Felicia Sutton        | 0         | 6            |
| 557 | Felix Gaffney         | 1         | 7            |
| 536 | Fernando Churchill    | 0         | 7            |
| 107 | Florence Woods        | 2         | 4            |
| 465 | Floyd Gandy           | 0         | 7            |
| 47  | Frances Parker        | 0         | 4            |
| 425 | Francis Sikes         | 0         | 6            |
| 443 | Francisco Skidmore    | 0         | 8            |
| 329 | Frank Waggoner        | 0         | 6            |
| 514 | Franklin Troutman     | 0         | 11           |
| 369 | Fred Wheat            | 1         | 2            |
| 597 | Freddie Duggan        | 1         | 7            |
| 429 | Frederick Isbell      | 0         | 3            |
| 518 | Gabriel Harder        | 0         | 8            |
| 155 | Gail Knight           | 2         | 6            |
| 324 | Gary Coy              | 1         | 8            |
| 498 | Gene Sanborn          | 0         | 1            |
| 314 | George Linton         | 0         | 11           |
| 231 | Georgia Jacobs        | 0         | 9            |
| 356 | Gerald Fultz          | 0         | 11           |
| 161 | Geraldine Perkins     | 0         | 7            |
| 207 | Gertrude Castillo     | 0         | 7            |
| 497 | Gilbert Sledge        | 1         | 7            |
| 213 | Gina Williamson       | 1         | 4            |
| 103 | Gladys Hamilton       | 0         | 10           |
| 486 | Glen Talbert          | 0         | 6            |
| 242 | Glenda Frazier        | 0         | 9            |
| 415 | Glenn Pullen          | 0         | 6            |
| 56  | Gloria Cook           | 1         | 8            |
| 470 | Gordon Allard         | 0         | 8            |
| 114 | Grace Ellis           | 1         | 10           |
| 472 | Greg Robins           | 1         | 8            |
| 335 | Gregory Mauldin       | 1         | 5            |
| 550 | Guy Brownlee          | 1         | 11           |
| 264 | Gwendolyn May         | 1         | 7            |
| 342 | Harold Martino        | 0         | 14           |
| 368 | Harry Arce            | 0         | 11           |
| 523 | Harvey Guajardo       | 0         | 5            |
| 138 | Hazel Warren          | 0         | 8            |
| 53  | Heather Morris        | 2         | 9            |
| 487 | Hector Poindexter     | 0         | 6            |
| 241 | Heidi Larson          | 0         | 9            |
| 15  | Helen Harris          | 2         | 14           |
| 344 | Henry Billingsley     | 0         | 6            |
| 428 | Herbert Kruger        | 0         | 1            |
| 481 | Herman Devore         | 0         | 9            |
| 263 | Hilda Hopkins         | 1         | 8            |
| 186 | Holly Fox             | 1         | 13           |
| 377 | Howard Fortner        | 0         | 7            |
| 552 | Hugh Waldrop          | 0         | 6            |
| 561 | Ian Still             | 1         | 4            |
| 183 | Ida Andrews           | 0         | 5            |
| 76  | Irene Price           | 0         | 4            |
| 255 | Irma Pearson          | 0         | 7            |
| 575 | Isaac Oglesby         | 0         | 8            |
| 570 | Ivan Cromwell         | 1         | 2            |
| 351 | Jack Foust            | 0         | 5            |
| 235 | Jackie Lynch          | 0         | 6            |
| 420 | Jacob Lance           | 0         | 2            |
| 86  | Jacqueline Long       | 0         | 10           |
| 565 | Jaime Nettles         | 0         | 9            |
| 299 | James Gannon          | 0         | 8            |
| 146 | Jamie Rice            | 0         | 9            |
| 531 | Jamie Waugh           | 0         | 4            |
| 77  | Jane Bennett          | 0         | 6            |
| 45  | Janet Phillips        | 0         | 6            |
| 66  | Janice Ward           | 0         | 10           |
| 524 | Jared Ely             | 0         | 6            |
| 322 | Jason Morrissey       | 0         | 5            |
| 535 | Javier Elrod          | 0         | 13           |
| 450 | Jay Robb              | 1         | 8            |
| 58  | Jean Bell             | 1         | 8            |
| 200 | Jeanne Lawson         | 1         | 6            |
| 418 | Jeff East             | 0         | 11           |
| 416 | Jeffery Pinson        | 0         | 8            |
| 328 | Jeffrey Spear         | 0         | 10           |
| 265 | Jennie Terry          | 0         | 7            |
| 6   | Jennifer Davis        | 0         | 9            |
| 282 | Jenny Castro          | 1         | 3            |
| 374 | Jeremy Hurtado        | 1         | 9            |
| 464 | Jerome Kenyon         | 0         | 5            |
| 337 | Jerry Jordon          | 1         | 8            |
| 387 | Jesse Schilling       | 0         | 9            |
| 26  | Jessica Hall          | 0         | 8            |
| 215 | Jessie Banks          | 1         | 10           |
| 533 | Jessie Milam          | 1         | 8            |
| 427 | Jesus Mccartney       | 0         | 4            |
| 159 | Jill Hawkins          | 0         | 4            |
| 451 | Jim Rea               | 0         | 11           |
| 558 | Jimmie Eggleston      | 0         | 6            |
| 397 | Jimmy Schrader        | 0         | 10           |
| 250 | Jo Fowler             | 0         | 6            |
| 62  | Joan Cooper           | 0         | 7            |
| 164 | Joann Gardner         | 0         | 1            |
| 147 | Joanne Robertson      | 0         | 13           |
| 349 | Joe Gilliland         | 1         | 8            |
| 431 | Joel Francisco        | 1         | 6            |
| 300 | John Farnsworth       | 1         | 10           |
| 571 | Johnnie Chisholm      | 0         | 4            |
| 395 | Johnny Turpin         | 0         | 6            |
| 455 | Jon Wiles             | 0         | 8            |
| 353 | Jonathan Scarborough  | 0         | 7            |
| 560 | Jordan Archuleta      | 2         | 7            |
| 473 | Jorge Olivares        | 0         | 9            |
| 326 | Jose Andrew           | 0         | 1            |
| 307 | Joseph Joy            | 0         | 4            |
| 121 | Josephine Gomez       | 0         | 13           |
| 336 | Joshua Mark           | 1         | 9            |
| 230 | Joy George            | 0         | 8            |
| 49  | Joyce Edwards         | 0         | 3            |
| 350 | Juan Fraley           | 0         | 9            |
| 135 | Juanita Mason         | 1         | 6            |
| 64  | Judith Cox            | 1         | 5            |
| 69  | Judy Gray             | 1         | 9            |
| 89  | Julia Flores          | 0         | 5            |
| 574 | Julian Vest           | 0         | 6            |
| 52  | Julie Sanchez         | 1         | 8            |
| 545 | Julio Noland          | 0         | 8            |
| 176 | June Carroll          | 0         | 9            |
| 354 | Justin Ngo            | 2         | 7            |
| 13  | Karen Jackson         | 0         | 8            |
| 526 | Karl Seal             | 0         | 12           |
| 61  | Katherine Rivera      | 0         | 5            |
| 36  | Kathleen Adams        | 0         | 7            |
| 82  | Kathryn Coleman       | 0         | 7            |
| 71  | Kathy James           | 0         | 7            |
| 193 | Katie Elliott         | 1         | 9            |
| 272 | Kay Caldwell          | 0         | 5            |
| 357 | Keith Rico            | 0         | 2            |
| 546 | Kelly Knott           | 0         | 7            |
| 67  | Kelly Torres          | 0         | 7            |
| 563 | Ken Prewitt           | 0         | 9            |
| 315 | Kenneth Gooden        | 1         | 4            |
| 591 | Kent Arsenault        | 0         | 8            |
| 321 | Kevin Schuler         | 0         | 7            |
| 118 | Kim Cruz              | 0         | 6            |
| 24  | Kimberly Lee          | 0         | 7            |
| 586 | Kirk Stclair          | 0         | 8            |
| 194 | Kristen Chavez        | 0         | 5            |
| 214 | Kristin Johnston      | 1         | 10           |
| 290 | Kristina Chambers     | 0         | 6            |
| 547 | Kurt Emmons           | 0         | 5            |
| 424 | Kyle Spurlock         | 1         | 6            |
| 543 | Lance Pemberton       | 0         | 4            |
| 327 | Larry Thrasher        | 1         | 11           |
| 22  | Laura Rodriguez       | 1         | 10           |
| 162 | Lauren Hudson         | 1         | 3            |
| 192 | Laurie Lawrence       | 1         | 7            |
| 361 | Lawrence Lawton       | 2         | 8            |
| 270 | Leah Curtis           | 0         | 8            |
| 421 | Lee Hawks             | 1         | 6            |
| 259 | Lena Jensen           | 0         | 12           |
| 466 | Leo Ebert             | 0         | 7            |
| 460 | Leon Bostic           | 0         | 10           |
| 281 | Leona Obrien          | 0         | 2            |
| 405 | Leonard Schofield     | 1         | 9            |
| 442 | Leroy Bustamante      | 0         | 7            |
| 143 | Leslie Gordon         | 0         | 5            |
| 506 | Leslie Seward         | 0         | 10           |
| 492 | Lester Kraus          | 0         | 4            |
| 478 | Lewis Lyman           | 0         | 6            |
| 98  | Lillian Griffin       | 0         | 5            |
| 233 | Lillie Kim            | 0         | 5            |
| 3   | Linda Williams        | 0         | 6            |
| 11  | Lisa Anderson         | 1         | 6            |
| 458 | Lloyd Dowd            | 0         | 7            |
| 91  | Lois Butler           | 1         | 9            |
| 542 | Lonnie Tirado         | 0         | 5            |
| 189 | Loretta Carpenter     | 0         | 4            |
| 78  | Lori Wood             | 0         | 10           |
| 165 | Lorraine Stephens     | 0         | 4            |
| 373 | Louis Leone           | 1         | 12           |
| 83  | Louise Jenkins        | 1         | 7            |
| 145 | Lucille Holmes        | 0         | 9            |
| 402 | Luis Yanez            | 0         | 3            |
| 243 | Lydia Burke           | 0         | 7            |
| 166 | Lynn Payne            | 0         | 9            |
| 256 | Mabel Holland         | 0         | 10           |
| 293 | Mae Fletcher          | 0         | 10           |
| 408 | Manuel Murrell        | 0         | 11           |
| 499 | Marc Outlaw           | 0         | 11           |
| 236 | Marcia Dean           | 1         | 8            |
| 444 | Marcus Hidalgo        | 0         | 10           |
| 9   | Margaret Moore        | 1         | 5            |
| 267 | Margie Wade           | 2         | 9            |
| 7   | Maria Miller          | 0         | 7            |
| 246 | Marian Mendoza        | 0         | 5            |
| 44  | Marie Turner          | 1         | 5            |
| 80  | Marilyn Ross          | 1         | 10           |
| 441 | Mario Cheatham        | 1         | 5            |
| 588 | Marion Ocampo         | 0         | 7            |
| 178 | Marion Snyder         | 1         | 9            |
| 128 | Marjorie Tucker       | 0         | 11           |
| 312 | Mark Rinehart         | 0         | 7            |
| 240 | Marlene Welch         | 0         | 7            |
| 257 | Marsha Douglas        | 0         | 12           |
| 583 | Marshall Thorn        | 0         | 1            |
| 38  | Martha Gonzalez       | 0         | 8            |
| 383 | Martin Bales          | 0         | 6            |
| 413 | Marvin Yee            | 0         | 8            |
| 1   | Mary Smith            | 0         | 8            |
| 539 | Mathew Bolin          | 0         | 4            |
| 323 | Matthew Mahan         | 0         | 8            |
| 252 | Mattie Hoffman        | 1         | 4            |
| 226 | Maureen Little        | 0         | 10           |
| 482 | Maurice Crawley       | 0         | 10           |
| 553 | Max Pitt              | 0         | 4            |
| 254 | Maxine Silva          | 0         | 10           |
| 151 | Megan Palmer          | 0         | 8            |
| 188 | Melanie Armstrong     | 1         | 7            |
| 223 | Melinda Fernandez     | 0         | 6            |
| 30  | Melissa King          | 0         | 10           |
| 422 | Melvin Ellington      | 1         | 11           |
| 302 | Michael Silverman     | 0         | 10           |
| 445 | Micheal Forman        | 0         | 10           |
| 154 | Michele Grant         | 0         | 7            |
| 21  | Michelle Clark        | 1         | 14           |
| 448 | Miguel Betancourt     | 2         | 10           |
| 403 | Mike Way              | 0         | 8            |
| 60  | Mildred Bailey        | 2         | 7            |
| 508 | Milton Howland        | 1         | 4            |
| 239 | Minnie Romero         | 0         | 8            |
| 285 | Miriam Mckinney       | 0         | 7            |
| 292 | Misty Lambert         | 0         | 5            |
| 520 | Mitchell Westmoreland | 0         | 13           |
| 131 | Monica Hicks          | 0         | 11           |
| 576 | Morris Mccarter       | 2         | 7            |
| 258 | Myrtle Fleming        | 0         | 6            |
| 12  | Nancy Thomas          | 0         | 6            |
| 274 | Naomi Jennings        | 1         | 12           |
| 216 | Natalie Meyer         | 2         | 7            |
| 406 | Nathan Runyon         | 0         | 5            |
| 504 | Nathaniel Adam        | 0         | 10           |
| 532 | Neil Renner           | 1         | 9            |
| 238 | Nellie Garrett        | 0         | 6            |
| 549 | Nelson Christenson    | 0         | 5            |
| 362 | Nicholas Barfield     | 0         | 10           |
| 68  | Nicole Peterson       | 0         | 6            |
| 268 | Nina Soto             | 0         | 8            |
| 266 | Nora Herrera          | 0         | 13           |
| 94  | Norma Gonzales        | 1         | 6            |
| 411 | Norman Currier        | 1         | 7            |
| 277 | Olga Jimenez          | 0         | 10           |
| 449 | Oscar Aquino          | 0         | 2            |
| 37  | Pamela Baker          | 0         | 10           |
| 2   | Patricia Johnson      | 0         | 6            |
| 340 | Patrick Newsom        | 0         | 9            |
| 262 | Patsy Davidson        | 0         | 10           |
| 311 | Paul Trout            | 0         | 6            |
| 95  | Paula Bryant          | 0         | 3            |
| 133 | Pauline Henry         | 0         | 7            |
| 224 | Pearl Garza           | 0         | 10           |
| 475 | Pedro Chestnut        | 0         | 4            |
| 101 | Peggy Myers           | 1         | 7            |
| 271 | Penny Neal            | 0         | 4            |
| 585 | Perry Swafford        | 1         | 4            |
| 341 | Peter Menard          | 0         | 7            |
| 393 | Philip Causey         | 0         | 11           |
| 385 | Phillip Holm          | 0         | 6            |
| 93  | Phyllis Foster        | 0         | 11           |
| 273 | Priscilla Lowe        | 0         | 9            |
| 79  | Rachel Barnes         | 0         | 3            |
| 505 | Rafael Abney          | 1         | 5            |
| 360 | Ralph Madrigal        | 0         | 9            |
| 494 | Ramon Choate          | 0         | 8            |
| 296 | Ramona Hale           | 1         | 10           |
| 437 | Randall Neumann       | 0         | 5            |
| 376 | Randy Gaither         | 0         | 7            |
| 509 | Raul Fortier          | 0         | 5            |
| 430 | Ray Houle             | 0         | 7            |
| 334 | Raymond Mcwhorter     | 1         | 8            |
| 34  | Rebecca Scott         | 0         | 9            |
| 168 | Regina Berry          | 1         | 12           |
| 500 | Reginald Kinder       | 0         | 7            |
| 593 | Rene Mcalister        | 0         | 4            |
| 182 | Renee Lane            | 0         | 7            |
| 137 | Rhonda Kennedy        | 0         | 11           |
| 489 | Ricardo Meador        | 0         | 9            |
| 305 | Richard Mccrary       | 0         | 6            |
| 491 | Rick Mattox           | 0         | 5            |
| 435 | Ricky Shelby          | 0         | 9            |
| 104 | Rita Graham           | 0         | 8            |
| 301 | Robert Baughman       | 0         | 4            |
| 185 | Roberta Harper        | 0         | 4            |
| 484 | Roberto Vu            | 0         | 8            |
| 100 | Robin Hayes           | 1         | 3            |
| 409 | Rodney Moeller        | 0         | 5            |
| 348 | Roger Quintanilla     | 0         | 11           |
| 521 | Roland South          | 1         | 10           |
| 519 | Ron Deluca            | 0         | 5            |
| 319 | Ronald Weiner         | 0         | 9            |
| 456 | Ronnie Ricketts       | 0         | 8            |
| 112 | Rosa Reynolds         | 0         | 11           |
| 65  | Rose Howard           | 0         | 6            |
| 204 | Rosemary Schmidt      | 0         | 9            |
| 580 | Ross Grey             | 0         | 7            |
| 363 | Roy Whiting           | 0         | 7            |
| 501 | Ruben Geary           | 0         | 6            |
| 90  | Ruby Washington       | 0         | 9            |
| 380 | Russell Brinson       | 0         | 11           |
| 19  | Ruth Martinez         | 0         | 9            |
| 347 | Ryan Salisbury        | 0         | 8            |
| 167 | Sally Pierce          | 0         | 10           |
| 584 | Salvador Teel         | 0         | 10           |
| 490 | Sam Mcduffie          | 0         | 5            |
| 177 | Samantha Duncan       | 0         | 6            |
| 358 | Samuel Marlow         | 0         | 4            |
| 16  | Sandra Martin         | 0         | 7            |
| 84  | Sara Perry            | 0         | 7            |
| 23  | Sarah Lewis           | 1         | 7            |
| 330 | Scott Shelley         | 1         | 4            |
| 392 | Sean Douglass         | 0         | 9            |
| 587 | Sergio Stanfield      | 1         | 5            |
| 590 | Seth Hannon           | 1         | 3            |
| 488 | Shane Millard         | 0         | 7            |
| 123 | Shannon Freeman       | 0         | 7            |
| 20  | Sharon Robinson       | 0         | 10           |
| 390 | Shawn Heaton          | 0         | 12           |
| 124 | Sheila Wells          | 0         | 4            |
| 294 | Shelly Watts          | 0         | 6            |
| 297 | Sherri Rhodes         | 0         | 10           |
| 119 | Sherry Marshall       | 0         | 14           |
| 27  | Shirley Allen         | 0         | 7            |
| 572 | Sidney Burleson       | 0         | 5            |
| 284 | Sonia Gregory         | 2         | 6            |
| 211 | Stacey Montgomery     | 1         | 11           |
| 180 | Stacy Cunningham      | 1         | 7            |
| 404 | Stanley Scroggins     | 0         | 10           |
| 247 | Stella Moreno         | 0         | 7            |
| 41  | Stephanie Mitchell    | 1         | 5            |
| 332 | Stephen Qualls        | 0         | 6            |
| 372 | Steve Mackenzie       | 0         | 11           |
| 316 | Steven Curley         | 0         | 6            |
| 197 | Sue Peters            | 0         | 8            |
| 8   | Susan Wilson          | 0         | 5            |
| 153 | Suzanne Nichols       | 0         | 9            |
| 120 | Sylvia Ortiz          | 1         | 7            |
| 229 | Tamara Nguyen         | 1         | 7            |
| 75  | Tammy Sanders         | 3         | 7            |
| 237 | Tanya Gilbert         | 0         | 9            |
| 203 | Tara Ryan             | 0         | 6            |
| 538 | Ted Breaux            | 0         | 6            |
| 54  | Teresa Rogers         | 0         | 10           |
| 592 | Terrance Roush        | 1         | 5            |
| 595 | Terrence Gunderson    | 0         | 6            |
| 206 | Terri Vasquez         | 0         | 9            |
| 253 | Terry Carlson         | 0         | 8            |
| 355 | Terry Grissom         | 1         | 3            |
| 122 | Thelma Murray         | 0         | 5            |
| 446 | Theodore Culp         | 0         | 4            |
| 72  | Theresa Watson        | 0         | 13           |
| 308 | Thomas Grigsby        | 0         | 10           |
| 110 | Tiffany Jordan        | 0         | 4            |
| 468 | Tim Cary              | 0         | 13           |
| 325 | Timothy Bunn          | 0         | 6            |
| 92  | Tina Simmons          | 0         | 6            |
| 386 | Todd Tan              | 0         | 6            |
| 452 | Tom Milner            | 1         | 8            |
| 459 | Tommy Collazo         | 0         | 8            |
| 291 | Toni Holt             | 0         | 3            |
| 401 | Tony Carranza         | 0         | 9            |
| 209 | Tonya Chapman         | 0         | 5            |
| 280 | Tracey Barrett        | 0         | 10           |
| 108 | Tracy Cole            | 1         | 7            |
| 589 | Tracy Herrmann        | 0         | 9            |
| 417 | Travis Estep          | 1         | 9            |
| 436 | Troy Quigley          | 0         | 12           |
| 496 | Tyler Wren            | 1         | 7            |
| 540 | Tyrone Asher          | 0         | 6            |
| 149 | Valerie Black         | 0         | 5            |
| 195 | Vanessa Sims          | 0         | 6            |
| 286 | Velma Lucas           | 0         | 7            |
| 218 | Vera Mccoy            | 0         | 7            |
| 483 | Vernon Chapa          | 0         | 3            |
| 158 | Veronica Stone        | 0         | 9            |
| 201 | Vicki Fields          | 0         | 9            |
| 251 | Vickie Brewer         | 1         | 9            |
| 382 | Victor Barkley        | 0         | 6            |
| 116 | Victoria Gibson       | 0         | 7            |
| 414 | Vincent Ralston       | 0         | 10           |
| 244 | Viola Hanson          | 1         | 8            |
| 289 | Violet Rodriquez      | 0         | 11           |
| 581 | Virgil Wofford        | 0         | 7            |
| 35  | Virginia Green        | 0         | 6            |
| 184 | Vivian Ruiz           | 0         | 9            |
| 598 | Wade Delvalle         | 0         | 4            |
| 562 | Wallace Slone         | 0         | 8            |
| 339 | Walter Perryman       | 0         | 9            |
| 87  | Wanda Patterson       | 1         | 9            |
| 462 | Warren Sherrod        | 0         | 11           |
| 370 | Wayne Truong          | 0         | 9            |
| 115 | Wendy Harrison        | 1         | 5            |
| 469 | Wesley Bull           | 0         | 10           |
| 578 | Willard Lumpkin       | 0         | 4            |
| 303 | William Satterfield   | 0         | 8            |
| 219 | Willie Howell         | 1         | 6            |
| 359 | Willie Markham        | 1         | 7            |
| 212 | Wilma Richards        | 0         | 7            |
| 190 | Yolanda Weaver        | 1         | 8            |
| 174 | Yvonne Watkins        | 0         | 5            |
| 479 | Zachary Hite          | 1         | 5            |